import type { GeneratedFile, ProjectProfile } from "../types.js";
import { commentBlock, markdownBlock, renderHeadroomMarkdown, renderLoopEngineeringMarkdown, renderMcpServersSnippet, renderReferenceMarkdown, renderRulesMarkdown, renderSkillMarkdown, renderSkillsMarkdown, renderSubagentsMarkdown, renderWorkflowPlaybookMarkdown } from "./helpers.js";
import type { GenerateForTargetsOptions } from "./index.js";
import { buildMcpCommand, renderMcpConfig } from "./mcpConfig.js";

function renderAgents(profile: ProjectProfile, options: GenerateForTargetsOptions = {}): string {
  return [
    "# AGENTS.md",
    "",
    "These repository instructions were generated by `agent-workflow-scaffold`.",
    "",
    markdownBlock("codex", renderRulesMarkdown(profile, profile.rules)),
    "",
    markdownBlock(
      "codex",
      [
        "## Subagent Role Guidance",
        "",
        "Use `.codex/skills/" + `${profile.projectId}-workflow/references/subagents.md` + "` to split larger tasks across workflow, implementation, review, and documentation roles.",
        "",
        "Use `.codex/skills/" + `${profile.projectId}-workflow/references/skills.md` + "` to review baseline and optional skill recommendations before adding project workflow capabilities.",
        "",
        "Use `.codex/skills/" + `${profile.projectId}-workflow/references/workflow-playbook.md` + "` for task definition, plan analysis, verification, review, Git, PR, and worktree workflow.",
        ...(options.loopEngineering
          ? [
              "",
              "Use `.codex/skills/" + `${profile.projectId}-workflow/references/loop-engineering.md` + "` when the user explicitly asks for Loop Engineering or a bounded agent loop."
            ]
          : []),
        ...(options.headroom?.enabled
          ? [
              "",
              "Use `.codex/skills/" + `${profile.projectId}-workflow/references/headroom.md` + "` when the task involves long logs, large diffs, large tool outputs, or explicit Headroom context compression."
            ]
          : [])
      ].join("\n")
    ),
    ""
  ].join("\n");
}

function renderCodexConfig(profile: ProjectProfile): string {
  return [
    "# Project-local Codex configuration.",
    "",
    commentBlock(
      "codex",
      [
        "[[hooks.SessionStart]]",
        'matcher = "startup|resume|clear|compact"',
        "",
        "[[hooks.SessionStart.hooks]]",
        'type = "command"',
        "command = '/usr/bin/python3 \"$(git rev-parse --show-toplevel)/.codex/hooks/repo_policy.py\"'",
        "timeout = 10",
        'statusMessage = "正在加载项目 AI 协作规则"',
        "",
        "[[hooks.PreToolUse]]",
        'matcher = "^(Bash|RunCommand|run_command|apply_patch|Edit|Write|MultiEdit|SearchReplace|DeleteFile|delete_file)$"',
        "",
        "[[hooks.PreToolUse.hooks]]",
        'type = "command"',
        "command = '/usr/bin/python3 \"$(git rev-parse --show-toplevel)/.codex/hooks/repo_policy.py\"'",
        "timeout = 10",
        'statusMessage = "正在检查项目安全策略"',
        "",
        renderMcpConfig("codex", profile)
      ].join("\n")
    ),
    ""
  ].join("\n");
}

function renderRepoPolicy(profile: ProjectProfile): string {
  const protectedPaths = JSON.stringify(profile.rules.protectedPaths);
  const envPaths = JSON.stringify(profile.rules.envSensitivePaths);
  return [
    "#!/usr/bin/env python3",
    commentBlock(
      "codex",
      [
        "import json",
        "import re",
        "import sys",
        "",
        `PROTECTED_PATHS = ${protectedPaths}`,
        `ENV_SENSITIVE_PATHS = ${envPaths}`,
        "DESTRUCTIVE = [",
        "    re.compile(r'(^|[;&|])\\s*git\\s+reset\\s+--hard(\\s|$)'),",
        "    re.compile(r'(^|[;&|])\\s*git\\s+checkout\\s+--(\\s|$)'),",
        "    re.compile(r'(^|[;&|])\\s*rm\\s+-rf(\\s|$)'),",
        "    re.compile(r'(^|[;&|])\\s*sudo(\\s|$)'),",
        "]",
        "",
        "def read_payload():",
        "    raw = sys.stdin.read().strip()",
        "    if not raw:",
        "        return {}",
        "    try:",
        "        data = json.loads(raw)",
        "    except json.JSONDecodeError:",
        "        return {}",
        "    return data if isinstance(data, dict) else {}",
        "",
        "def command_from_payload(payload):",
        "    for key in ('command',):",
        "        if isinstance(payload.get(key), str):",
        "            return payload[key]",
        "    for key in ('tool_input', 'input', 'params', 'arguments'):",
        "        value = payload.get(key)",
        "        if isinstance(value, dict) and isinstance(value.get('command'), str):",
        "            return value['command']",
        "    return ''",
        "",
        "def emit(message, decision=None):",
        "    payload = {'hookSpecificOutput': {'hookEventName': 'PreToolUse', 'additionalContext': message}}",
        "    if decision:",
        "        payload['permissionDecision'] = decision",
        "        payload['permissionDecisionReason'] = message",
        "        payload['hookSpecificOutput']['permissionDecision'] = decision",
        "        payload['hookSpecificOutput']['permissionDecisionReason'] = message",
        "    sys.stdout.write(json.dumps(payload))",
        "",
        "payload = read_payload()",
        "command = command_from_payload(payload)",
        "for pattern in DESTRUCTIVE:",
        "    if pattern.search(command):",
        "        emit('Blocked destructive command by generated repo policy.', 'deny')",
        "        sys.exit(0)",
        "if command:",
        "    for protected in PROTECTED_PATHS:",
        "        if protected and protected in command:",
        "            emit('Generated repo policy: avoid editing protected/generated path: ' + protected)",
        "            sys.exit(0)",
        "    for env_path in ENV_SENSITIVE_PATHS:",
        "        if env_path and env_path in command:",
        "            emit('Generated repo policy: environment-sensitive path touched; verify env mappings and run targeted build.')",
        "            sys.exit(0)"
      ].join("\n")
    ),
    ""
  ].join("\n");
}

export function generateCodex(profile: ProjectProfile, options: GenerateForTargetsOptions = {}): GeneratedFile[] {
  const mcp = buildMcpCommand();
  const headroom = options.headroom;
  const mcpJson = renderMcpServersSnippet([
    { name: "agent-workflow-scaffold", command: mcp.command, args: mcp.args, cwd: profile.rootPath },
    ...(headroom?.enabled ? [{ name: "headroom", command: headroom.command, args: headroom.args }] : [])
  ]);
  return [
    { target: "codex", relativePath: "AGENTS.md", content: renderAgents(profile, options), mode: "managed-text" },
    { target: "codex", relativePath: ".codex/config.toml", content: renderCodexConfig(profile), mode: "managed-text" },
    { target: "codex", relativePath: ".codex/hooks/repo_policy.py", content: renderRepoPolicy(profile), mode: "managed-text" },
    {
      target: "codex",
      relativePath: `.codex/skills/${profile.projectId}-workflow/SKILL.md`,
      content: renderSkillMarkdown(profile, "codex", options),
      mode: "managed-text"
    },
    {
      target: "codex",
      relativePath: `.codex/skills/${profile.projectId}-workflow/references/project-rules.md`,
      content: renderReferenceMarkdown(profile, "codex"),
      mode: "managed-text"
    },
    {
      target: "codex",
      relativePath: `.codex/skills/${profile.projectId}-workflow/references/subagents.md`,
      content: renderSubagentsMarkdown(profile, "codex"),
      mode: "managed-text"
    },
    {
      target: "codex",
      relativePath: `.codex/skills/${profile.projectId}-workflow/references/skills.md`,
      content: renderSkillsMarkdown(profile, "codex"),
      mode: "managed-text"
    },
    {
      target: "codex",
      relativePath: `.codex/skills/${profile.projectId}-workflow/references/workflow-playbook.md`,
      content: renderWorkflowPlaybookMarkdown(profile, "codex"),
      mode: "managed-text"
    },
    ...(options.loopEngineering
      ? [
          {
            target: "codex" as const,
            relativePath: `.codex/skills/${profile.projectId}-workflow/references/loop-engineering.md`,
            content: renderLoopEngineeringMarkdown(profile, "codex"),
            mode: "managed-text" as const
          }
        ]
      : []),
    ...(headroom?.enabled
      ? [
          {
            target: "codex" as const,
            relativePath: `.codex/skills/${profile.projectId}-workflow/references/headroom.md`,
            content: renderHeadroomMarkdown(profile, "codex", headroom),
            mode: "managed-text" as const
          }
        ]
      : []),
    {
      target: "codex",
      relativePath: ".codex/mcp.agent-workflow.json",
      content: `${JSON.stringify(mcpJson, null, 2)}\n`,
      mode: "structured-json",
      jsonMerge: mcpJson
    }
  ];
}
