import type { LocalSkill, ProjectProfile, SkillRecommendation, SkillRecommendationCategory } from "../types.js";

interface RecommendationRule {
  id: string;
  name: string;
  category: SkillRecommendationCategory;
  description: string;
  reason: (profile: ProjectProfile) => string;
  installPolicy: SkillRecommendation["installPolicy"];
  applies: (profile: ProjectProfile) => boolean;
}

function hasAnyDependency(profile: ProjectProfile, names: string[]): boolean {
  const dependencies = new Set([...profile.dependencies, ...profile.devDependencies]);
  return names.some((name) => dependencies.has(name));
}

function hasAnyDoc(profile: ProjectProfile, patterns: RegExp[]): boolean {
  return profile.docFiles.some((file) => patterns.some((pattern) => pattern.test(file)));
}

function localSkillById(skills: LocalSkill[]): Map<string, LocalSkill> {
  return new Map(skills.map((skill) => [skill.id, skill]));
}

const RULES: RecommendationRule[] = [
  {
    id: "project-workflow",
    name: "project workflow skill",
    category: "baseline",
    installPolicy: "generated",
    description: "Project-local workflow skill generated by this scaffold for the selected target.",
    reason: (profile) => `Always generated as ${profile.projectId}-workflow to capture repository rules, commands, subagents, and MCP usage.`,
    applies: () => true
  },
  {
    id: "writing-plans",
    name: "writing-plans",
    category: "baseline",
    installPolicy: "recommended",
    description: "Plan multi-step implementation work before editing.",
    reason: () => "Recommended as a baseline workflow guard for multi-step Agent changes.",
    applies: () => true
  },
  {
    id: "requesting-code-review",
    name: "requesting-code-review",
    category: "baseline",
    installPolicy: "recommended",
    description: "Run code-review checks before merging or after major changes.",
    reason: () => "Recommended as a baseline review workflow for generated Agent configurations and project code changes.",
    applies: () => true
  },
  {
    id: "skill-creator",
    name: "skill-creator",
    category: "project",
    installPolicy: "recommended",
    description: "Create or update reusable skills with stable instructions and references.",
    reason: () => "Useful because this scaffold creates project-local skills and may need future skill iteration.",
    applies: () => true
  },
  {
    id: "find-skills",
    name: "find-skills",
    category: "optional",
    installPolicy: "optional",
    description: "Discover installable skills for a task or project domain.",
    reason: () => "Optional discovery helper. The scaffold should recommend it, not install or copy user-global skills by default.",
    applies: () => true
  },
  {
    id: "browser-control-in-app-browser",
    name: "browser:control-in-app-browser",
    category: "optional",
    installPolicy: "optional",
    description: "Verify local frontend UI in a browser.",
    reason: (profile) => `Detected frontend stack: ${profile.techStack.join(", ") || profile.projectType}. Use for UI verification when the runtime supports browser skills.`,
    applies: (profile) =>
      profile.projectType === "umi-react" ||
      profile.projectType === "h5" ||
      profile.projectType === "management" ||
      hasAnyDependency(profile, ["react", "umi", "@umijs/max", "antd", "antd-mobile"])
  },
  {
    id: "openspec",
    name: "openspec",
    category: "optional",
    installPolicy: "optional",
    description: "Use OpenSpec workflows when the repository has spec-driven development artifacts.",
    reason: () => "Detected OpenSpec-like documentation or dependency markers.",
    applies: (profile) => hasAnyDependency(profile, ["openspec"]) || hasAnyDoc(profile, [/openspec/i])
  },
  {
    id: "documents-documents",
    name: "documents:documents",
    category: "optional",
    installPolicy: "optional",
    description: "Create and edit Word/docx style documents.",
    reason: () => "Detected document-oriented files or docs-heavy repository structure.",
    applies: (profile) => hasAnyDoc(profile, [/\.(docx?|rtf)$/i]) || profile.docFiles.length >= 8
  },
  {
    id: "pdf-pdf",
    name: "pdf:pdf",
    category: "optional",
    installPolicy: "optional",
    description: "Read, create, inspect, render, and verify PDFs.",
    reason: () => "Detected PDF assets or document workflows.",
    applies: (profile) => hasAnyDoc(profile, [/\.pdf$/i])
  },
  {
    id: "spreadsheets-spreadsheets",
    name: "spreadsheets:spreadsheets",
    category: "optional",
    installPolicy: "optional",
    description: "Work with xlsx/csv/tsv spreadsheets.",
    reason: () => "Detected spreadsheet assets or data-heavy docs.",
    applies: (profile) => hasAnyDoc(profile, [/\.(xlsx?|csv|tsv)$/i])
  },
  {
    id: "presentations-presentations",
    name: "presentations:presentations",
    category: "optional",
    installPolicy: "optional",
    description: "Create, edit, render, verify, and export PowerPoint decks.",
    reason: () => "Detected presentation assets or proposal-heavy docs.",
    applies: (profile) => hasAnyDoc(profile, [/\.(pptx?|key)$/i])
  },
  {
    id: "lark-shared",
    name: "lark-shared",
    category: "optional",
    installPolicy: "optional",
    description: "Initialize and authenticate Lark/Feishu CLI usage.",
    reason: () => "Detected Lark/Feishu-related project markers. Keep enterprise skills optional unless the project explicitly needs them.",
    applies: (profile) =>
      profile.docFiles.some((file) => /lark|feishu|飞书/i.test(file)) ||
      hasAnyDependency(profile, ["@larksuiteoapi/node-sdk", "@larksuite-oapi/node-sdk"])
  },
  {
    id: "dws",
    name: "dws",
    category: "optional",
    installPolicy: "optional",
    description: "Operate DingTalk product capabilities through configured enterprise tooling.",
    reason: () => "Detected DingTalk-related project markers. Keep enterprise skills optional unless the project explicitly needs them.",
    applies: (profile) =>
      profile.docFiles.some((file) => /dingtalk|dingding|钉钉/i.test(file)) ||
      hasAnyDependency(profile, ["dingtalk-jsapi", "dingtalk-jsapi-plus"])
  }
];

export function recommendSkills(profile: ProjectProfile, localSkills: LocalSkill[] = []): SkillRecommendation[] {
  const localById = localSkillById(localSkills);
  return RULES.filter((rule) => rule.applies(profile)).map((rule) => {
    const local = localById.get(rule.id);
    return {
      id: rule.id,
      name: rule.name,
      category: rule.category,
      description: rule.description,
      reason: rule.reason(profile),
      installPolicy: rule.installPolicy,
      installed: Boolean(local),
      localPath: local?.skillPath,
      source: local?.source
    };
  });
}
